/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MechanicRouteImport } from './routes/mechanic'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MechanicIndexRouteImport } from './routes/mechanic.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as MechanicEarningsRouteImport } from './routes/mechanic.earnings'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerHistoryRouteImport } from './routes/customer.history'
import { Route as CustomerRequestServiceRouteImport } from './routes/customer.request.$service'

const MechanicRoute = MechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicIndexRoute = MechanicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MechanicRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const MechanicEarningsRoute = MechanicEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => MechanicRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRequestServiceRoute = CustomerRequestServiceRouteImport.update({
  id: '/request/$service',
  path: '/request/$service',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/mechanic': typeof MechanicRouteWithChildren
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/mechanic/earnings': typeof MechanicEarningsRoute
  '/customer/': typeof CustomerIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/customer/request/$service': typeof CustomerRequestServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/mechanic/earnings': typeof MechanicEarningsRoute
  '/customer': typeof CustomerIndexRoute
  '/mechanic': typeof MechanicIndexRoute
  '/customer/request/$service': typeof CustomerRequestServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/mechanic': typeof MechanicRouteWithChildren
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/mechanic/earnings': typeof MechanicEarningsRoute
  '/customer/': typeof CustomerIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/customer/request/$service': typeof CustomerRequestServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/mechanic'
    | '/customer/history'
    | '/customer/profile'
    | '/mechanic/earnings'
    | '/customer/'
    | '/mechanic/'
    | '/customer/request/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer/history'
    | '/customer/profile'
    | '/mechanic/earnings'
    | '/customer'
    | '/mechanic'
    | '/customer/request/$service'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/mechanic'
    | '/customer/history'
    | '/customer/profile'
    | '/mechanic/earnings'
    | '/customer/'
    | '/mechanic/'
    | '/customer/request/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  MechanicRoute: typeof MechanicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mechanic': {
      id: '/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof MechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic/': {
      id: '/mechanic/'
      path: '/'
      fullPath: '/mechanic/'
      preLoaderRoute: typeof MechanicIndexRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/mechanic/earnings': {
      id: '/mechanic/earnings'
      path: '/earnings'
      fullPath: '/mechanic/earnings'
      preLoaderRoute: typeof MechanicEarningsRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/request/$service': {
      id: '/customer/request/$service'
      path: '/request/$service'
      fullPath: '/customer/request/$service'
      preLoaderRoute: typeof CustomerRequestServiceRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerRequestServiceRoute: typeof CustomerRequestServiceRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerRequestServiceRoute: CustomerRequestServiceRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface MechanicRouteChildren {
  MechanicEarningsRoute: typeof MechanicEarningsRoute
  MechanicIndexRoute: typeof MechanicIndexRoute
}

const MechanicRouteChildren: MechanicRouteChildren = {
  MechanicEarningsRoute: MechanicEarningsRoute,
  MechanicIndexRoute: MechanicIndexRoute,
}

const MechanicRouteWithChildren = MechanicRoute._addFileChildren(
  MechanicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  MechanicRoute: MechanicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
